name: Smoke Test Application
on:
  workflow_call:
    inputs:
      appServiceDefaultHostName:
        required: true
        type: string

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          $container = New-PesterContainer `
            -Path 'scripts/Website.Tests.ps1' `
            -Data @{ HostName = '${{ inputs.appServiceDefaultHostName }}' }
          Invoke-Pester `
            -Container $container `
            -CI
        name: Run smoke tests
        shell: pwsh
