name: deploy-auto-website-suite
concurrency: auto-bicep

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      resourceGroupName: rg_sb_eastus_89803_1_171095341434
    steps:
      - name: Set env
        run: echo "resourceGroupName=rg_sb_eastus_89803_1_171095341434"
      # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  validate:
    needs: [lint, setup]
    uses: ./.github/workflows/validate.yml
    with:
      resourceGroupName: ${{ needs.setup.outputs.resourceGroupName}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  preview:
    needs: [validate, setup]
    uses: ./.github/workflows/preview.yml
    with:
      resourceGroupName: ${{ needs.setup.outputs.resourceGroupName}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: [preview, setup]
    uses: ./.github/workflows/deploy.yml
    with:
      resourceGroupName: ${{ needs.setup.outputs.resourceGroupName}}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
