name: deploy-auto-website-suite
concurrency: auto-bicep

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  validate:
    needs: lint
    uses: ./.github/workflows/validate.yml
    with:
      resourceGroupName: rg_sb_eastus_89803_1_171095341434
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  preview:
    needs: validate
    uses: ./.github/workflows/preview.yml
    with:
      resourceGroupName: rg_sb_eastus_89803_1_171095341434
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: preview
    uses: ./.github/workflows/deploy.yml
    with:
      resourceGroupName: rg_sb_eastus_89803_1_171095341434
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
